### ISSUE TITLE
Mah sword dissapeared!!! (angry face)

### ISSUE THREAD

**Issue by ghost** [ImagineCraft/Hattie#3]
:p all fine ^^

But I was at the enderman farm today, trying out the plugin and my sword dissapeared. 
- My inventory was full and I was not wearing any armor
- I typed in the /hat command with my sword in my main hand and according to chat it was equiped as helmet
- My character picked up some more enderpearls in my main hand after I typed the command
- I tried to get my sword back by typing the command once again, hoping it would replace the stack of enderpearls in my main hand with my sword
- Instead of that, I ended up with 1 ender pearl in my helmet slot and 1 stack of ender pearls in my hand. The sword was gone.

I think this has to do with the only one item in your helmet slot instead of the full stack. When I ran the command a second time, it took one ender pearl from the stack of ender pearls I was holding. This ender pearl got placed on my head, but because only one item was taken from the stack, it did not clear any inventory space for my sword. I think that was the thing that went wrong, could be wrong though.

-Cyber

**Comment by kriation** [comment]
Interesting!

@Ekzim, should we limit the code so that only specific block types can be worn as hats?

**Comment by Ekzim** [comment]
@kriation yes, when I was hearing of CyberDrain's unfortunate mishap, I was thinking why would you put a sword on your head?  lol.  So yes, I think limiting it to actual blocks that can be placed in game would be much better than trying to accomodate tools/weapons/misc items like enderpearls, etc.

**Comment by kriation** [comment]
After reading through the issue summary, I realized that there's an edge case that isn't being handled properly. 

Consider the condition of a fully inventory (mix of stacks and items), a worn hat (regardless of type), and a different item in the main hand. 

@Ekzim, how do you want to handle the situation where the user wants to switch the hat type, and the item worn as hat has no where in the inventory to go? Should we drop it into the world or let it vanish?

**Comment by Ekzim** [comment]
@kriation Drop it on the ground.

**Comment by ghost** [comment]
Replying to the "I was thinking why would you put a sword on your head? lol."

I use it to repair my tools, believe it or not :p. When I got to the enderman farm, I put one tool in my off hand and one on my head. The mending effect still works and Im a happy man ^^

Besides, people also use the /hat command with banners or others items that look interesting. Yeah I think we should not just limit to blocks IMO. Atleast I dont see why items could be a problem and blocks not.

**Comment by kriation** [comment]
> Besides, people also use the /hat command with banners or others items that look interesting. Yeah I think we should not just limit to blocks IMO. Atleast I dont see why items could be a problem and blocks not.

Would it be worth setting up a privilege gradient for the types of blocks that a a player can wear as a hat, or too much of a pain to manage? @Ekzim?
